version: "3"
services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: user_admin
            POSTGRES_PASSWORD: password_admin
            POSTGRES_DB: db
            SERVICE_TAGS: dev
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        networks:
            - app-network
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        volumes:
            - ./backend:/app/
            - /app/node_modules
        ports:
            - "8080:8080"
        networks:
            - app-network
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        stdin_open: true
        volumes:
            - ./frontend:/app/
            - /app/node_modules
        ports:
            - "80:3000"
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
      driver: bridge
